name: Prueba_m

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Iniciar Docker
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Construir imagen Docker
      run: docker build -t Prueba_m .

    - name: Etiquetar imagen Docker
      run: docker tag Prueba_m consesionario:latest

    - name: Empujar imagen Docker a Docker Hub
      run: docker push consesionario:latest
