on: push
name: Test_M
jobs:
  deploy:
    name: Test_Master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build y push a docker
      uses: docker/build-push-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }}
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{ github.sha }}
          
     
