name: Test_M

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Iniciar Docker
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Construir imagen Docker
      run: docker build -t concesionario_producion .

    - name: Etiquetar imagen Docker
      run: docker tag concesionario_producion santiago725/consesionario:latest

    - name: Empujar imagen Docker a Docker Hub
      run: docker push santiago725/consesionario:latest
     
